name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test (JVM)

    steps:
      - uses: actions/checkout@v3

      - name: Set up GraalVM for Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.2'
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Confirm Java version
        run: java -version

      - name: Make executable
        run: chmod +x backend/mvnw

      - name: Build with Maven (JVM mode)
        run: cd backend && ./mvnw clean verify
