name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - 'Makefile'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test (Makefile)

    env:
      QUARKUS_PROFILE: qa  # ✅ This ensures Quarkus uses the 'qa' profile if supported

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GraalVM for Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.2'
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Confirm Java version
        run: java -version

      - name: Make wrapper executable
        run: chmod +x backend/mvnw

      - name: Build backend with QA profile
        run: make build

      - name: Run tests
        run: make test
