name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test (JVM)

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Make executable
        run: chmod +x backend/mvnw

      - name: Build with Maven (JVM mode)
        run: cd backend && ./mvnw clean verify
