name: Deploy UI to QA

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy Frontend to QA
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ACCOUNT_ID: 020157571320

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Docker and Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Deploy frontend using Makefile
        run: make deploy-qa-ui
