name: Deploy Backend to QA

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'Makefile'
      - '.github/workflows/deploy-backend.yml'

  workflow_dispatch:  # Allow manual deployments

env:
  AWS_REGION: us-east-1
  ACCOUNT_ID: "020157571320"
  BACKEND_IMAGE_NAME: zooby-backend
  BACKEND_ECR_URI: 020157571320.dkr.ecr.us-east-1.amazonaws.com/zooby-backend
  ECS_CLUSTER: zooby-qa-cluster
  ECS_SERVICE: zooby-backend
  QUARKUS_PROFILE: qa

jobs:
  deploy-backend:
    name: Build, Push, and Deploy Backend
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Needed for OIDC
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM for Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.2'
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Confirm Java version
        run: java -version

      - name: Set short Git SHA
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Dump OIDC Token Context
        run: |
          echo "OIDC URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "Token present? ${ACTIONS_ID_TOKEN_REQUEST_TOKEN:+yes}"

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/zooby-github-actions-role
          role-session-name: zoobyBackendDeploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $BACKEND_ECR_URI

      - name: Build native image
        run: make native

      - name: Build backend Docker image
        run: make build-backend-docker

      - name: Push backend Docker image
        run: make push-backend-image

      - name: Force ECS service update
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Print deployed version
        run: |
          echo "✅ Backend deployed version: $GIT_SHA"
