name: Deploy UI to QA

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'Dockerfile'
      - 'Makefile'
      - '.github/workflows/deploy-ui-qa.yml'

  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy Frontend to QA
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      ACCOUNT_ID: 020157571320

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Dump GitHub OIDC context
        run: |
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "ACTOR: $GITHUB_ACTOR"
          echo "SHA: $GITHUB_SHA"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "env ACCOUNT_ID: ${{ env.ACCOUNT_ID }}"
          echo "env AWS_REGION: ${{ env.AWS_REGION }}"
          echo "Role to assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/zooby-github-actions-role"

      - name: Assume AWS Role with OIDC
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::020157571320:role/zooby-github-actions-role
          aws-region: us-east-1
          role-session-name: github-actions

      - name: Install Docker and Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Deploy frontend using Makefile
        run: make deploy-qa-ui
