name: Deploy UI to QA

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'
      - 'Makefile'
      - '.github/workflows/deploy-ui-qa.yml'
  pull_request:
    branches: [main]
    paths:
      - 'infra/**'
      - 'Makefile'
      - '.github/workflows/deploy-ui-qa.yml'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::020157571320:role/zooby-github-actions-role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Terraform Init
        run: make tf-init TERRAFORM_ENV=qa

      - name: Terraform Validate
        run: make tf-validate TERRAFORM_ENV=qa

      - name: Terraform Plan
        run: make tf-plan TERRAFORM_ENV=qa

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: make tf-apply TERRAFORM_ENV=qa
