name: Terraform


on:
  push:
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Validate
        run: |
          cd infra
          terraform init
          terraform validate
        env:
          AWS_S3_FORCE_PATH_STYLE: true