name: Terraform CI

on:
  push:
    paths:
      - 'infra/**'
      - 'Makefile'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2
    name: Format, Validate & Plan

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Format Check
        run: cd infra && terraform fmt -check

      - name: Validate (Makefile)
        run: make tf-validate TERRAFORM_ENV=local

      - name: Plan (Makefile)
        run: make tf-plan TERRAFORM_ENV=local

      - name: Upload plan artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-output
          path: infra/.terraform
