name: Terraform Pull Request Plan

on:
  pull_request:
    branches: [main]
    paths:
      - 'infra/**'
      - 'Makefile'
      - '.github/workflows/terraform-pr.yml'

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::020157571320:role/zooby-github-actions-role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Terraform Init / Validate / Plan
        run: |
          make tf-init TERRAFORM_ENV=qa
          make tf-validate TERRAFORM_ENV=qa
          make tf-plan TERRAFORM_ENV=qa | tee infra/plan.out

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/plan.out
