name: Terraform Workflow

on:
  push:
    paths:
      - 'infra/**'
      - 'Makefile'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init
        run: cd infra && terraform init -backend-config="key=qa/terraform.tfstate"

      - name: Validate
        run: terraform validate -var-file="infra/environments/qa.tfvars"

      - name: Plan
        run: terraform plan -var-file="infra/environments/qa.tfvars"

      - name: Upload plan artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-output
          path: infra/.terraform

      - name: Apply
        if: github.event_name == 'push' && success()
        run: terraform apply -auto-approve -var-file="infra/environments/qa.tfvars"
